seed: 42
map_size: 1000.0
tau0: 1.0
T_steps: 200

num_uav: 3
num_gu: 20
num_sat: 9

users_obs_max: 20
sats_obs_max: 3
visible_sats_max: 3
visible_sats_min: 2
nbrs_obs_max: 4

uav_height: 100.0
sat_height: 500000.0
v_max: 30.0
a_max: 5.0
d_safe: 20.0
boundary_mode: reflect

task_arrival_rate: 1.0e6
task_arrival_poisson: true

b_acc: 5.0e5
b_sat_total: 5.0e6
sat_cpu_freq: 2.0e9
gu_tx_power: 0.02
pathloss_mode: free_space

doppler_observed: true
doppler_enabled: false
energy_enabled: false
fading_enabled: false
interference_enabled: false
enable_bw_action: false
fixed_satellite_strategy: true
N_RF: 1

buffer_size: 4000
num_mini_batch: 32
ppo_epochs: 4

early_stop_enabled: true
early_stop_min_updates: 20
early_stop_window: 5
early_stop_patience: 10
early_stop_min_delta: 0.001
